spring.application.name=inventario

server.port=8090

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=validate

springdoc.swagger-ui.layout=BaseLayout

# Expande solo los títulos de los endpoints
springdoc.swagger-ui.docExpansion=list

# Agrega un cuadro para filtrar por tags
springdoc.swagger-ui.filter=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.protocol=smtp
spring.mail.username=${CORREO}
spring.mail.password=${PASW_APLI}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

jwt.secret=${JWT_SECRET}


